from collections.abc import Iterator
from datetime import date, datetime
from decimal import Decimal
from typing import Any, Generic, TypeVar

from part.models import Part

_T = TypeVar("_T")

class _QuerySet(Generic[_T]):
    def filter(self, *args: Any, **kwargs: Any) -> _QuerySet[_T]: ...
    def exclude(self, *args: Any, **kwargs: Any) -> _QuerySet[_T]: ...
    def order_by(self, *fields: str) -> _QuerySet[_T]: ...
    def only(self, *fields: str) -> _QuerySet[_T]: ...
    def select_related(self, *fields: str) -> _QuerySet[_T]: ...
    def values(self, *fields: str) -> _QuerySet[Any]: ...
    def annotate(self, **kwargs: Any) -> _QuerySet[_T]: ...
    def values_list(self, *fields: str) -> _QuerySet[Any]: ...
    def all(self) -> _QuerySet[_T]: ...
    def get(self, **kwargs: Any) -> _T: ...
    def count(self) -> int: ...
    def __iter__(self) -> Iterator[_T]: ...
    def __getitem__(self, index: int | slice) -> Any: ...

class _Manager(Generic[_T]):
    def select_for_update(self) -> _QuerySet[_T]: ...
    def values_list(self, *fields: str, **kwargs: Any) -> _QuerySet[Any]: ...
    def all(self) -> _QuerySet[_T]: ...
    def filter(self, *args: Any, **kwargs: Any) -> _QuerySet[_T]: ...
    def only(self, *fields: str) -> _QuerySet[_T]: ...
    def get(self, **kwargs: Any) -> _T: ...
    def count(self) -> int: ...
    def order_by(self, *fields: str) -> _QuerySet[_T]: ...

class StockLocation:
    pk: int
    name: str
    description: str
    parent_id: int | None
    pathstring: str
    stock_items: _Manager[StockItem]
    children: _Manager[StockLocation]
    objects: _Manager[StockLocation]

class StockItem:
    def __init__(self, **kwargs: Any) -> None: ...
    pk: int
    part_id: int
    part: Part
    quantity: Decimal
    location_id: int | None
    location: StockLocation | None
    serial: str | None
    batch: str | None
    status: int
    notes: str
    updated: datetime
    packaging: str
    link: str
    expiry_date: date | None
    delete_on_deplete: bool
    objects: _Manager[StockItem]
    def set_status(self, status: int) -> bool: ...
    def full_clean(self) -> None: ...
    def save(self, *, user: Any = ...) -> None: ...
    def add_stock(self, quantity: Decimal, user: Any, notes: str = ...) -> bool: ...
    def take_stock(self, quantity: Decimal, user: Any, notes: str = ...) -> bool: ...
    def move(self, location: StockLocation, notes: str, user: Any) -> bool: ...
    def refresh_from_db(self) -> None: ...
